### ISSUE TITLE
D2S Design QA: Accordian Design QA

### ISSUE THREAD

**Issue by AliHayder5** [desk-design-system/d2s#192]
<img width="1192" alt="image" src="https://github.com/desk-design-system/d2s/assets/137146640/6ef156b9-330d-483b-98f1-85533db2deed">

1. Padding should be 24 from left right and 20px from top bottom. It is 12 currently.
2. The Title font should be base(medium). It is sm right now.
3. The left icon should be 28. The spacing between left icon and Title is 8px
4. There should be a right slow before chevron with hight 24. The slot and icon should be 8px apart.
5. There should be a shadow sm to the accordian card.
6. There should be another color prop with the white and gradient options already conveyed with Haseeb.

Here are the two states of accordian open and closed:
![image](https://github.com/desk-design-system/d2s/assets/137146640/c09369b5-c88d-4593-82bf-2da858b21c54)

Design Link:
https://www.figma.com/file/tkoUko4LEyFwpYCICBwXY4/D2S?type=design&node-id=1213-14023&mode=design

**Comment by junaidjahan** [comment]
This issue is fixed in f0f5d0b1f3e4b3c8558660287c233cc235eca4a8
