### ISSUE TITLE
D2S Design QA: Badge

### ISSUE THREAD

**Issue by AliHayder5** [desk-design-system/d2s#196]
Props:
There are only two props mentioned in design. Size & Color. The build version has many unecessary props. PLease use props as per design.

Sizes: xs, base
Color: See attached image or design

Design:
For badge with right cross: 1. the margin between cross and text should be 4px. The padding for base is 8px horizontal and 4px veritcla. The padding for xs is 6px horizontal and 2px vertical/

https://www.figma.com/file/tkoUko4LEyFwpYCICBwXY4/D2S?type=design&node-id=1055-14621&mode=design
![image](https://github.com/desk-design-system/d2s/assets/137146640/2d9f3e3a-709b-4e3f-882e-f59dad272498)
![image](https://github.com/desk-design-system/d2s/assets/137146640/2737e82b-ba21-4341-9c6a-e3714f9d1722)

**Comment by AliHayder5** [comment]
Done

**Comment by hbghaffar01** [comment]
done
