### ISSUE TITLE
Drop down in inner header avatar is a bit distorted

### ISSUE THREAD

**Issue by Roohallah-RD** [desk-design-system/d2s#90]
- Half of the drop down goes in the screen
- Below is a gif for reference:
[Screencast from 31-05-2023 15:09:27.webm](https://github.com/desk-design-system/d2s/assets/129150133/42167376-70d3-49f1-b756-2e0f50e1419b)

**Comment by Muhammad-Arslan-Arif-RD** [comment]
@Roohallah-RD 
Fixed and resolved.
